name: Publish Image to Docker Hub
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t alexandrakoroleva/q_learning:latest
      - name: publish
        run: |
          docker login -u alexandrakoroleva -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push alexandrakoroleva/q_learning:latest
      
    

